language: node_js
node_js:
- '7'
script:
- npm test
- npm run build:prod
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jgpuzzo@metrocast.net
  organization: puzzo.sandbox
  space: development
  on:
    repo: react-tools/react-form
  password:
    secure: GzKjOeGm+59Gg/oouwJ+xnG52OexkNWf9WhDo4MpPtAhQShW91ZH6UU65rNTS8PcV5gpdgTi/coV+YubvDvBul/O87+t6FZyKDSEUSd0lLKHfzoZzV8hBvzvjOVNFRBd9if49Yv7qKja9BHi73Pkn+DEQRabU4eyCV58tTOXJWIiWN4yVmJoBgBWepZmD8iY4qFkk8XjYt1uk03jjXyAgT62lMyni+hAE3OORSyoQurFldDOZ17GpaLqRzr/aSbTcvOzNl3bkQ+dsbOF7gGNwOG/GqKniJDHEh7+Fj2703rLXPaqtHxyNn3aO6Ep/AIDK1gd7f6SAdM9kh26cWML9xN7d1q7AxuEZH/d/XEHnsRa2UPAFKMEaR3gcmiqjQOr9sCMNdXDP9I6LA5mO1Fp6/jm9UTu7kCQfIZmnjGqHM41XjZl9kdDA7cW4h1PCvlG4JSl5XCDWbBLxunkqJUrDu2tLdmPY7xb6DPTzqudv50CC0n5cNxCce6tArPd5F4EaOOOsAr76CkguE38qaPPYYnOb28qL98tbwasXsdxlw3d/JAStxlmqn+L4FKFg+LwLbqsaEbjBnhlxq1ysQiw5UfT3+27M17P1UJD18xXPtutInw8iAIGroIStjCXO0eory4sm6OowSgLhArYsrMtPi4ldkO3VLQv5V7OitZrARI=
